//Code generated at 1572612275

static void MORSTAIRS_MAP_EVENTS_F();
static void OVERWORLD_MAP_EVENTS_F();
static void DUNGEON_MAP_EVENTS_F();
static void FORGEVIELLE_MAP_EVENTS_F();
#define MORSTAIRS_MAP_EVENTS MORSTAIRS_MAP_EVENTS_F();
#define OVERWORLD_MAP_EVENTS OVERWORLD_MAP_EVENTS_F();
#define DUNGEON_MAP_EVENTS DUNGEON_MAP_EVENTS_F();
#define FORGEVIELLE_MAP_EVENTS FORGEVIELLE_MAP_EVENTS_F();

GENERATE_FUNC_LEADING_TO_DESTINATION(MORSTAIRS_MAP_TO_OVERWORLD_MAP_0, 12, 9, MORSTAIRS_MAP_MAP_PATH, MORSTAIRS_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(OVERWORLD_MAP_TO_MORSTAIRS_MAP_1, 17, 5, OVERWORLD_MAP_MAP_PATH, OVERWORLD_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(DUNGEON_MAP_TO_MORSTAIRS_MAP_2, 16, 3, DUNGEON_MAP_MAP_PATH, DUNGEON_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(MORSTAIRS_MAP_TO_DUNGEON_MAP_3, 29, 5, MORSTAIRS_MAP_MAP_PATH, MORSTAIRS_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(DUNGEON_MAP_TO_OVERWORLD_MAP_4, 23, 20, DUNGEON_MAP_MAP_PATH, DUNGEON_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(OVERWORLD_MAP_TO_DUNGEON_MAP_5, 19, 7, OVERWORLD_MAP_MAP_PATH, OVERWORLD_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(FORGEVIELLE_MAP_TO_OVERWORLD_MAP_6, 12, 9, FORGEVIELLE_MAP_MAP_PATH, FORGEVIELLE_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(OVERWORLD_MAP_TO_FORGEVIELLE_MAP_7, 26, 6, OVERWORLD_MAP_MAP_PATH, OVERWORLD_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(FORGEVIELLE_MAP_TO_OVERWORLD_MAP_8, 19, 14, FORGEVIELLE_MAP_MAP_PATH, FORGEVIELLE_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(OVERWORLD_MAP_TO_FORGEVIELLE_MAP_9, 27, 6, OVERWORLD_MAP_MAP_PATH, OVERWORLD_MAP_EVENTS)
GENERATE_FUNC_LEADING_TO_DESTINATION(OVERWORLD_MAP_TO_OVERWORLD_MAP_10, 9, 8, OVERWORLD_MAP_MAP_PATH, OVERWORLD_MAP_EVENTS)

static void MORSTAIRS_MAP_EVENTS_F() { 
	ADD_EVENT_AT_POSITION(11, 9, OVERWORLD_MAP_TO_MORSTAIRS_MAP_1)
	ADD_EVENT_AT_POSITION(29, 5, DUNGEON_MAP_TO_MORSTAIRS_MAP_2)
	MORSTAIRS_MAP_MUS
}

static void OVERWORLD_MAP_EVENTS_F() { 
	ADD_EVENT_AT_POSITION(17, 5, MORSTAIRS_MAP_TO_OVERWORLD_MAP_0)
	ADD_EVENT_AT_POSITION(19, 7, DUNGEON_MAP_TO_OVERWORLD_MAP_4)
	ADD_EVENT_AT_POSITION(26, 6, FORGEVIELLE_MAP_TO_OVERWORLD_MAP_6)
	ADD_EVENT_AT_POSITION(27, 6, FORGEVIELLE_MAP_TO_OVERWORLD_MAP_8)
	ADD_EVENT_AT_POSITION(7, 8, OVERWORLD_MAP_TO_OVERWORLD_MAP_10)
	OVERWORLD_MAP_MUS
}

static void DUNGEON_MAP_EVENTS_F() { 
	ADD_EVENT_AT_POSITION(16, 3, MORSTAIRS_MAP_TO_DUNGEON_MAP_3)
	ADD_EVENT_AT_POSITION(23, 20, OVERWORLD_MAP_TO_DUNGEON_MAP_5)
	DUNGEON_MAP_MUS
}

static void FORGEVIELLE_MAP_EVENTS_F() { 
	ADD_EVENT_AT_POSITION(11, 9, OVERWORLD_MAP_TO_FORGEVIELLE_MAP_7)
	ADD_EVENT_AT_POSITION(19, 15, OVERWORLD_MAP_TO_FORGEVIELLE_MAP_9)
	FORGEVIELLE_MAP_MUS
}
